#!/bin/bash

gnome-terminal -x python controlBox.py

gnome-terminal -x python simpleCV_3_noOutput.py

gnome-terminal -x python beatDetect.py

gnome-terminal -x python IMUInterface.py

gnome-terminal -x python pyOSCServer.py

gnome-terminal -x python footPedal.py
