#!/bin/bash
# this opens all sensors if executed from an Ubuntu gnome-terminal instance

gnome-terminal -x python simpleCV_3_noOutput.py

gnome-terminal -x python beatDetect.py

gnome-terminal -x python IMUInterface.py

gnome-terminal -x python pyOSCServer.py

gnome-terminal -x python footPedal.py
